phoenix-rtos/phoenix-rtos-build

- build-core-ia32-qemu.sh
There was no error checking in the build core
The same should probably be added to other ```build-core-*``` files.
> Added 'set -e' to check for errors

- build-core-armv7-stm32.sh
- build.sh
This pull request allow to compile targets without full phoenix environment with „all” command. Now it's not needed to have phoenix-rtos-ports or root-skel in project. Also I remove need of any project specific commands.
Added b_prepare hook, that will be executed before any other actions will be performed. It would be beneficial if any project specific action will need to be performed before any other action will be performed.
Also it adds some tweaks to receive git version on repositories saved into /etc/git-version
Also removed unneeded install command on stm32 core. 
I verified if this not breaks project builds.
@kaman confirmed that this not breaks build on MacOS systems.
> Stm32 tweaks

- build-core-armv7-stm32.sh
Now filesystems depend on devices (stm32-multi.h header), so devices need to be build first.
> stm32: Build filesystems after devices

- Makefile.armv7
Sorry, merged too soon: https://stackoverflow.com/questions/12970596/gcc-4-8-does-og-imply-g
> Revert "Makefile.armv7: removed repeated -g flag"

- build-core-ia32-generic.sh
Now there is bug:
```
TARGET=ia32-generic
Installing dummyfs into /sbin 
/tmp/phoenix-rtos-project/_build/ia32-generic/prog.stripped//ext2 binary does not exist 
```
> build-core-ia32-generic.sh: removed install ext2

- build-core-armv7m7-imxrt106x.sh
The build fails because _boot binary is created when copying phoenixd before _boot directory creation.
> armv7: fix no _boot directory

- Makefile.common
- build.sh
Common include dir should not be passed to kernel. It hides issue from https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/121
Also removed passing include from build.sh – it duplicates parameter from Makefile
> Remove passing include dir to kernel

- toolchain/build-toolchain.sh
- toolchain/gcc-9.3.0-02-i386-pc-phoenix.patch
- toolchain/gcc-9.3.0-03-riscv64-phoenix.patch
Adding `riscv*-*-phoenix` target to gcc:
- ensured `phoenix` is a STD define (provided by toolchain, no need to add `-Dphoenix` for riscv targets anymore)
- removed `libgloss` link dependency
WARN: **this changes the riscv toolchain name to riscv64-phoenix-gcc**
> toolchain: add proper riscv toolchain

- build.sh
* remove `-Dphoenix` from `CFLAGS` - this define is no longer needed after introducing proper RISC-V
toolchain
**after this change new toolchain for `riscv64` targets will need to be used**
* better 'clean' command support
This is only partial work, all created/changed files should lie either in
`_build/$TARGET` or `_fs/$TARGET`, so cleaning should be as simple as
removing these directories.
Most of the remaining work needs to be done in `phoenix-rtos-ports` and
in `plo`.
**please use REBASE MERGE STRATEGY when merging this pull request**
> Build enhancements

- build-core-armv7m7-imxrt106x.sh
When building target armv7m7-imxrt106x without "clean" option the build breaks:
"make: *** empty string invalid as file name.  Stop."
This is because in build-core-armv7m7-imxrt106x.sh make commands variable
$CLEAN is in quotation marks ("$CLEAN"). Removing them solves the issue.
> imxrt: fix build break when no clean option provided

- Makefile.armv7m
This PR is associated with https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/159
> armv7m: section .text=0 and .bss=0x20000000 are not longer obligatory for linker

- Makefile.common
- Makefile.host
- build-core-armv7a7-imx6ull.sh
- build-core-armv7m7-imxrt106x.sh
- build.sh
I added host-pc target for building code for host with our buildsystem.
Along with this change, I changed hostutils to build using new common Makefile but I preserved the old method for build with build.sh script. To switch to new Makefile, much more changes is required:
1. In phoenix-rtos-build make possible to build for many architecture – env is polluted by exports connected with main TARGET
2. In phoenix-rtos-ports make possible to build without extensive external env – would be great if only TARGET will be needed for normal build.
> Add host-pc to accepted platform. Use old hostutils build

- Makefile.armv7a
- Makefile.common
- build-core-armv7a9-zynq7000.sh
Changes in this PR are associated with the following PRs:
- https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/184
- https://github.com/phoenix-rtos/libphoenix/pull/78
> arm: rename arm to armv7a & add build file for zynq-7000

- Makefile.armv7m
Flag `-q` adds `.rel` sections into to elf file. These sections are not needed for kernel and plo. `-q` is removed to reduce size of elf's files.
> armv7m: remove '-q' linker flag from kernel & plo

- Makefile.common
- Makefile.host
- makes/binary.mk
Enable "--whole-archive" while linking our internal libs
JIRA: CI-50
> makes: support constructors in static libraries

- Makefile.ia32
This makes lwip compilation possible.
JIRA: CI-45
> makes: ia32: fix LDFLAGS

- Makefile.common
In `bash`, the option `-e` is needed for the correct interpretation of `'\n'`. In `dash` this option is the default. 
`echo -n` works in `bash` and do not works in `dash`.
Why `$(info )` and not `echo`?
> Makefile: echo fixed for portability

- makes/check-target.mk
Now the available TARGETS are sorted and printed on separate lines.
@nalajcie What do you think about creating a variable e.g. 
```
TARGET_FAMSUB := $(TARGET_FAMILY)-$(TARGET_SUBFAMILY)
```
and use it instead of
```
$(TARGET_FAMILY)-$(TARGET_SUBFAMILY)
```
> Makefile: corrected message about available TARGETS

- Makefile.armv7m
-I${SRCDIR} with empty {SRCDIR} causes that -Imthumb was passed. 
-mthumb are without leading, so invalid too.
Remove unneeded -I and fix mthumb.
> Fix invalid passing -mthumb flag

- build-core-armv7m4-stm32l4x6.sh
Add building corelibs for armv7m4-stm32l4x6 target
It's required for rotating rectangle example in user space.
JIRA: PD-119
> armv7m4-stm32l4x6: add building corelibs

- Makefile.armv7a
- Makefile.armv7m
- Makefile.ia32
- Makefile.riscv64
The change causes apps on imxrt to crash after second launch.
This reverts commit ef8a1166499d7dc3a925ffab5b26e70976ef6f43.
DONE: BES-169
The commit ef8a116 introduces problems in imxrt106x, causing apps to reset system after invoking sysexec 2 times.
Reverting commit ef8a116 fixes problem with launching apps using sysexec for imxrt platform based projects.
> imxrt: revert linking crtbegin.o/crtend.o

- build-core-host-pc.sh
- build-core-ia32-generic.sh
Now tests for `ia32-generic` and `host-pc` are partially build as a `core` target. As there is a `test` target there is no need to further use of the `core`.
Changes won't break CI - in the `test` target make with `install` is invoked which is now equivalent to `all install`
> build: remove tests building from core

- scripts/program-stm32l4x6.sh
program script uses absolute predefined path to opemocd scripts before.
Now it will be relative to openocd installation.
JIRA: ISC-118
To have openocd support for new hardware you have to compile it from sources as releases are too rare. Standard path for local builds is /usr/local but it don't have to be there. This patch changes hardcoded path to relative from binary (it's auto resolved by openocd)
Change fixes script error in my environment where openocd is self compiled in another directory. 
Also, possible to system installed openocd on newest distros (on 7.03 openocd 0.11.0 with support of new cpus and programmers are was released)
> scripts: Fix stm32l4 program script

- Makefile.armv7a
- Makefile.ia32
- build.sh
Stop-gap for phoenix-rtos/phoenix-rtos-project#138
> build: add NDEBUG, add /tmp creation by default

- build-core-armv7m7-imxrt106x.sh
JIRA: BES-177
This change causes lwip to be built by default.
We use lwip in at least two projects on imxrt1064, using different drivers, so it has already been proven to be working. We should build it by default.
> armv7m7-imxrt106x: Build lwip by default

- Makefile.armv7a
- Makefile.armv7m
- Makefile.ia32
- Makefile.riscv64
This reverts commit 8744ba3bba8f3c5935f2945e92d8a2065bc59e83.
New toolchain builds crtstuff from gcc with -fPIC option so no absoulte
relocation in data section occurs, so issues on imxrt platforms should
not occur now.
This commit is workaround for stm32l4x6 targets with invalid place of
_init/fini_array_start/end symbols when _init/fini_array is empty.
JIRA: ISC-118
Reverts the revert  which was needed due to issues on imxrt platform with absolute reloations connected with crtstuff. With new toolchain builds all should work as expected
This is workaround for issue probably in linker/linker script.
When init/fini array is empty sometimes it's outside the data segment and kernel cannot do relocation on this symbol. 
Example content of program section and _fini_array_address:
```
Elf file …
```
> Revert "imxrt: revert linking crtbegin.o/crtend.o"

- makes/binary.mk
- makes/static-lib.mk
In case we have the same file names on different dirs and we want to
install one of them in PREFIX_H, the file to be installed was decided on
sub-Makefile include order.
The error was caught during CI build:
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/139/checks?check_run_id=3677396404
(while building `imx6ull` `i2c.h` is being installed from `multi/stm32l1-multi/i2c.h` instead of `i2c/common/i2c.h`)
JIRA: DTR-152
> makes: fix headers install rule to be applied only for chosen headers

- toolchain/build-toolchain.sh
I looked through the `build-toolchain.sh` script and noticed that `strip` is executed only for files in the `bin` directory.
However in the `libexec/gcc/<target>/9.3.0` directory there are files which significantly affect the size of the toolchain e.g.
```
ls -l arm-phoenix/libexec/gcc/arm-phoenix/9.3.0
-rwxrwxrwx 1 root root 216M Aug 24 13:15 cc1
-rwxrwxrwx 1 root root 227M Aug 24 13:15 cc1plus
-rwxrwxrwx 1 root root 4.1M Aug 24 13:15 collect2
drwxrwxrwx 2 root root 4.0K Aug 24 13:15 install-tools
-rwxrwxrwx 1 root root 1005 Aug 24 13:15 liblto_plugin.la
lrwxrwxrwx 1 root root   22 Aug 24 13:15 liblto_plugin.so -> liblto_plugin.so.0.0.0
lrwxrwxrwx 1 root root   22 Aug 24 13:15 liblto_plugin.so.0 -> liblto_plugin.so.0.0.0
-rwxrwxrwx 1 root root 443K Aug 24 13:15 liblto_plugin.so.0.0.0 …
```
> build-toolchain: changed list of files to strip

- Makefile.riscv64
Makefile: riscv: add DEBUG variable check
Documentation, including quickstarts need to be updated. There is a problem with running riscv-spike image using spike simulator. The user stack corrupted error occurs then. This change doesn't solve some known problem with kernel (fix is in progress), but the problem isn't invoked, when NDEBUG is set (building without debug option).
JIRA: PD-206
> Makefile: riscv: add DEBUG variable check

- build-core-armv7m4-stm32l4x6.sh
JIRA: ISC-126
This change is needed in order to build `phoenix-rtos-devices` repo after merging: https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/152
> armv7m4-stm32l4x6: Build libdummyfs before devices

- Makefile.common
This makes `__FILE__` macro being stripped from
/my/fancy/local/dir/phoenix-rtos-kernel/syscalls.c ->
/phoenix-rtos-kernel/syscalls.c
(please note that debug paths in unstripped binaries are unaffected for
ease of use with GDB, for more repetitive builds we would need to change
that).
JIRA: CI-98
> makes: cflags: remove local dev path from macros

- build-core-armv7a9-zynq7000.sh
`unity` is built before other repositories 
JIRA: PD-216
Repositories other than `phoenix-rtos-tests` use `unity` library.
> zynq7000: add building unity library

- Makefile.armv7a
- Makefile.armv7m
- Makefile.common
- Makefile.host
- Makefile.ia32
- Makefile.riscv64
Default optimisation level can be overwritten by build.project by
defining OLVL variable.
It is required for some targets to define Os instead of default O2
level to decrease flashimg size.
JIRA: ISC-164
Add new parameter OLVL which accepts -O flags. All other flags is filtered. This allows to change optimisation level of whole system from project configuration.
> makes: Add OLVL to change optimisation level

- Makefile.armv7m
- Makefile.common
- scripts/strip.py
Relocation sections have references to symtab, which is not needed for
relocation process in kernel. Script is needed for remove this
refferences to allow strip removing symtab
Also it removes rel.text entirely as it's not needed
JIRA: ISC-129
Add strip wrapper to remove references from relocation sections to symtab and then run strip
This way it allows strip to removal of big symtab.
armv7m targets will use this strip wrapper to produce stripped binaries
This change is needed for decreasing binary size on NOMMU targets that perform dynamic relocation in kernel.
Some statistics and infos below:
1. Differnces with size:
- armv7m4-stm32l4x6
| Program  | Current | Removal only .rel.text | Removal with script |
| ------------- | ------------- | ------------- | ------------- |
| …
> makes: Add script wrapping strip

- build.sh
JIRA: ISM-46
When build directory is is not a git repository write "not available" into git-version and continue build.
Previously running build inside non-git project directory resulted in aborted build with multiple git commands errors or writing git information from git repository that was in project directory parent.
This allows using phoenix-rtos-build for ad-hoc projects that are automatically created using scripts.
> allow building projects without git repository

- build-core-armv7a9-zynq7000.sh
Phoenixd is needed when flashing system image on zynq7000 target.
JIRA: RTOS-184
> armv7a9-zynq7000: add building host utils with phoenixd

- toolchain/build-toolchain.sh
- Enable thread local storage while building toolchain
JIRA: RTOS-209
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/339
https://github.com/phoenix-rtos/libphoenix/pull/195.
> toolchain: add enable-tls flag

- toolchain/build-toolchain.sh
Used by ar, ranlib, objcopy, strip when operating on .a file. When enabled, all timestamps, GID, UID is setted to zero for checksum determinism.
It's not strictly required for reproducable binary but allows to have deterministic .a files - it should be the same on every machine when compiled from same source code.
JIRA: ISC-222
In this change, binutils flag was added to improve building artifacts reprodicibility
While looking at binary reproducibilty I found that .a files on different machines differs with timestamps in header. Then I found that flag and I found it's useful in terms of build reprodicibility. 
It's not critical, because those timestapmts are not included in binary but I found' that's good mechanism.
Results of md5sum on libphoenix.a from  two consecutive builds with old …
> toolchain: Enable deterministic archive

- build.sh
Remove redundant backlashes from grep.
In newer versions of grep those backslashes cause a warning.
> Remove redundant backslashes

- Makefile.common
DONE: RTOS-442
Make -Og optional on DEBUG, not mandatory
To allow testing builds with debugs/asserts enabled without destroying performance and code size
> Do not change optimization for DEBUG builds

- build.sh
> Validate build options.

- Makefile.host
- makes/binary.mk
- host-generic-pc: install unstripped binaries into rootfs by default
Needed to provide meaningful backtraces on sanitizer errors.
- makes: add option to install unstripped binaries into rootfs
Needed for host-generic-pc to provide meaningful backtraces on sanitizer
errors.
Fixes: phoenix-rtos/phoenix-rtos-project#797
> Add option to install unstripped binaries into rootfs and enable it for host-generic-pc

- toolchain/build-toolchain.sh
- toolchain/gcc-9.5.0-01-arm-phoenix-multilib.patch
- toolchain/gcc-9.5.0-02-i386-pc-phoenix.patch
- toolchain/gcc-9.5.0-03-riscv64-phoenix.patch
- toolchain/gcc-9.5.0-04-disable_tm.patch
- toolchain/gcc-9.5.0-05-arm-pic_crtstuff.patch
- toolchain/gcc-9.5.0-06-libstdcpp.patch
- toolchain/gcc-9.5.0-07-sparc-phoenix.patch
- toolchain/gcc-9.5.0-08-sparc-mno-pditr.patch
- toolchain/gcc-9.5.0-09-sparc-pic_crtstuff.patch
- toolchain: support building multilib versions of libphoenix
We need to include all supported multilib variants of libc in the toolchain
release.
- toolchain: bump to gcc-9.5
This is a bugfix release, no changes to patches are needed.
- toolchain: explicitly set c++ include dir inside sysroot
JIRA: CI-334
> Toolchain: update / prepare for external sysroot

- Makefile.common
Fixes building toolchain (multilib libphoenix via direct make).
JIRA: CI-334
> make: add PROJECT_PATH to CFLAGS includes only if non-empty

- Makefile.common
JIRA: DEND-32 DTR-408
This change enable possibility to pass WATCHDOG to kernel/plo build
While we want to deprecate BOARD_CONFIG env, we need to find a way to pass watchdog setting to kernel/plo. Decided to do so via env which is defaultly enabled. Need to be disabled directly when not wanted.
Also it enables WATCHDOG on armv7a7-imx6ull
Application to handle watchdog needed if watchdog wasn't enabled before. Alternatively - disable watchdog explicitly
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/847
https://github.com/phoenix-rtos/plo/pull/293
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/453
https://github.com/phoenix-rtos/phoenix-rtos-build/pull/163
> make: Add passing WATCHDOG as define

- Makefile.common
- build-core-armv7a7-imx6ull.sh
- build-core-armv7a9-zynq7000.sh
- build-core-armv7m4-stm32l4x6.sh
- build-core-armv7m7-imxrt105x.sh
- build-core-armv7m7-imxrt106x.sh
- build-core-armv7m7-imxrt117x.sh
- build-core-ia32-generic.sh
- build-core-riscv64-generic.sh
- build-core-sparcv8leon3-gr716.sh
- build.sh
- makes/setup-sysroot.mk
- target/host.mk
**WARN: change requires toolchain rebuild.**
Alternatively keep using toolchain sysroot.
JIRA: CI-334
> build: introduce per-project sysroot

- toolchain/build-toolchain.sh
JIRA: CI-377
Configure scripts treat some environment variables as overrides for command line options. This aborts build if those variables are set.
I decided to abort instead of doing unset so that we can easily see in what environments/platforms this could be an issue.  As I written in comments proper solution might be to unset those variables only for cross stages.
I was building toolchain with CC variable set to host compiler. It was building without issues. After libstdc++ was added c++ builds were failing due to missing include files.
```
from /build/source/_user/hellocpp/main.cpp:16:
/build/source/_build/ia32-generic-qemu/sysroot/include/c++/cwctype:50:10: fatal error: wctype.h: No such file or directory
50 | #include <wctype.h>
|          ^~~~~~~~~~
```
After some investigation I …
> toolchain: abort if environment is not valid

- target/sparcv8leon3.mk
Remove `-msoft-float` flag on GR712RC userspace code, to enable generating FP instructions
> sparcv8leon3: use FPU on GR712RC

- build-core-armv7m7-imxrt105x.sh
- build-core-armv7m7-imxrt106x.sh
- build-core-armv7m7-imxrt117x.sh
Change adds `libposixsrv` build which may be used optionally in `imxrt-multi` driver.
JIRA: RTOS-641
Change required by PR:
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/460
> Enable build of optional `libposixsrv on i.MX RT`

- build-core-armv7m4-stm32l4x6.sh
Change adds possibility to use optional `libposixsrv` in `stm32l4-multi` driver.
JIRA: RTOS-641
> Enable optional libposixsrv on STM32L4

- Makefile.common
Invoking GCC with `-fcommon` can hide common variable name collisions. Since GCC 10 `-fno-common` is default.
JIRA: DEND-177
> make: add -fno-common to CFLAGS

- scripts/run_project_tests.py
JIRA: CI-411
A script to run unity and pytest tests in a host environment for Phoenix-RTOS.
TARGET=host-generic-target ./phoenix-rtos-build/scripts/run_project_tests.py
Options:
- C - Set campaign to run
- c - Set path to config
- v - Enable verbose mode
- S - Stream the output of test on stdout
campaign_name:
unity:
- binary1 args
- binary2
pytest:
- path1 args
- path2
Need vm.map_rnd_bits set to 28
You can use: sudo sysctl vm.mmap_rnd_bits=28
due to the issue reported here: https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1032
> add setup and test execution script

- Makefile.common
- makes/check-env.mk
- makes/include-target.mk
- toolchain/build-toolchain.sh
Cherry-picking changes from master to release branch:
- toolchain: skip checking if build env is sane
- makes: make build env sanity checks optional
Needed for building toolchain (uses install-headers directly without build.sh
entrypoint).
> toolchain: fix building toolchain

- toolchain/gcc-9.5.0-05-arm-pic_crtstuff.patch
Cortex-A was incorrectly detected as Cortex-M resulting in building libgcc/crtstuff with compile options dedicated for NOMMU. These binaries were not runnable as for MMU targets we're stripping reloc sections during build.
JIRA: CI-453
> toolchain: fix arm cortex subvariant check

- Makefile.common
- build.sh
Export the STRIP variable to enable building ports on both MMU and NOMMU targets.
JIRA: RTOS-840
> update build system to export STRIP variable

- build.subr
`b_install` function will accept any number of source files and one destination directory, which mimics system tool `install`. This makes it possible to use glob expansions when invoking the function.
> build.subr: Make b_install accept multiple source files

- build-core-sparcv8leon3-generic.sh
- makes/include-target.mk
- target/sparcv8leon3.mk
> add sparcv8leon3-generic target

- toolchain/gcc-9.5.0-06-libstdcpp.patch
- toolchain/gcc-9.5.0-11-armv-r-phoenix-multilib.patch
Default GCC configuration chooses basic `armv7` multilib for both ARM A- and R-profile. However ARM-R does not have MMU and GCC-provided libs for this target must be compiled with appropriate PIC flags.
> toolchain: fix ARM R-profile multilib configuration

- toolchain/gcc-9.5.0-06-libstdcpp.patch
- toolchain/gcc-9.5.0-07-sparc-phoenix.patch
JIRA: RTOS-918
Add PIC flags to `libstdcpp` only when the mulitlib requires it.
Change `-fPIE` multilib flag to `-fPIC`
`libstdcpp` wasn't compiled with appriopriate flags on SPARC MMU platforms.
> toolchain: fix multilib flags for SPARC

- Makefile.common
Newer linker version(>-2.39) issues a warning if stack is executable. Setting -z stack-size without -z noexecstack can cause this issue. On Phoenix stack is currently never executable.
JIRA: RTOS-909
> build: add noexecstack flag

- toolchain/binutils-2.34-03-arm-phoenix-emul-fix.patch
Previously we defined armelf_phoenix emulation that wasn't used. This patch fixes the configuration to use it.
Additionally support in armelf_phoenix emulation for shared libs is added.
JIRA: RTOS-911
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/586
> !toolchain/ld: change arm emul

- Makefile.common
Newer versions of GCC take advantage of strict aliasing rule that we break, without explicitely warning about it.
JIRA: RTOS-927
> Makefile.common: add -fno-strict-aliasing

- scripts/image_builder.py
- scripts/nvm_config.py
> image_builder: improve diagnostic/error messages

- scripts/image_builder.py
With this change you can hand-craft commands which normally would be parsed by `image_builder.py`, eg:
`%app flash0 -x psh;-i;/etc/rc.psh ddr ddr;nonexistent` (will not generate corresponding `alias`, will not add `psh` to the target image automatically)
This usage is discouraged and should be used only in testing and some extremely hackish use cases.
JIRA: CI-494
> image builder: allow passing commands directly by using `%` prefix

- Makefile.common
Fix ld version parsing not working for version format `<Major>.<Minor>.<Patch>`
Add explicit error when version cannot be parsed.
JIRA: RTOS-959
> Makefile.common: fix ld version parsing

- build-core-aarch64a53-zynqmp.sh
- makes/include-target.mk
- scripts/mkimg-boot-zynqmp.sh
- target/aarch64.mk
- toolchain/binutils-2.43-04-aarch64-phoenix.patch
- toolchain/build-toolchain.sh
- toolchain/gcc-9.5.0-12-aarch64-phoenix.patch
Added toolchain for compiling code to AArch64 (Arm in 64-bit mode) and scripts for building Phoenix RTOS for ZynqMP platform.
> toolchain: add toolchain for AArch64

- build.sh
> build: export CXXFLAGS

- target/armv8m.mk
> MCXN94x: Handle selection of CPU1 (cc flags + define)

- toolchain/build-toolchain.sh
Use absolute path to toolchain patches, relatively to script dir
Our build toolchain script is almost ready to build toolchain without entering phoenix-rtos-build/toolchain/ directory prior to execute build-toolchain.sh script. It makes our buildsystem cleaner. After this change, toolchain building instruction can be simplified:
```
./phoenix-rtos-build/toolchain/build-toolchain.sh i386-pc-phoenix ~/toolchains/i386-pc-phoenix
(...)
```
instead of:
```
(cd phoenix-rtos-build/toolchain/ && ./build-toolchain.sh i386-pc-phoenix ~/toolchains/i386-pc-phoenix)
(...)
```
> toolchain: Allow build toolchain from any working dir

- target/aarch64.mk
This fixes system hang on Zynq Ultrascale+ after update to GCC 14.2.
The newer GCC version implements atomic operations using a function that may use LSE extension instructions. It decided whether to use these instructions using a flag in memory (`__aarch64_have_lse_atomics`). However, because we do not use glibc, the flag was never initialized. Additionally, because in kernel the `.bss` segment is not initialized to 0, system would hang non-deterministically on real hardware (on QEMU uninitialized memory reads as 0, so it would never hang).
With `-mno-outline-atomics` flag, GCC only uses LSE instructions if they are mandatory for the architecture given in `-mcpu` flag. LSE is mandatory starting from Arm v8.1.
Because we do not use glibc, the "outline atomics" feature would require …
> aarch64: add -mno-outline-atomics compilation flag

- Makefile.common
There are some useful warning flags, which are enabled in internal projects, like -Wundef and -Wshadow.
This commit adding  `-Wundef` to our build system
Enable `-Wundef`
> Makefile.common: add -Wundef

- Makefile.common
* Treat every warning as an error - to catch problems early in CI.
* add optional `USER_CFLAGS`/ `USER_CXXFLAGS` to override CFLAGS on per-project basis.
Potentially breaking - if forks contain code with warnings.
How to fix: fix your code - or add `USER_CFLAGS=-Wno-error` to the project file.
JIRA: CI-556
> !Makefile.common: add -Werror

- target/riscv64.mk
This is a workaround for libphoenix being built with the toolchain, where RISCV_ISA_STRING is not set. The build will use the default risc-v configuration until proper multilib support is added.
Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/1360
> riscv64.mk: don't check RISCV_ISA_STRING when NOCHECKENV=1
