phoenix-rtos/phoenix-rtos-build

build.sh

I also suggest removing unnecessary shift in the for loop.

build.sh: change checking function existence

---

scripts/mkimg-imxrt.sh
scripts/mkimg-stm32.sh

Substitute non-portable `stat -c` with `wc -c`.

Fix mkimg on MacOS

---

Makefile.common
build.sh

JIRA: CI-18
I also changed some printfs but is only suggestion and can be discarded
Needed by ci: [add test runner job #61](https://github.com/phoenix-rtos/phoenix-rtos-project/pull/61)

test: add test target to build.sh

---

Makefile.common
build-core-armv7a7-imx6ull.sh
build-core-armv7a9-zynq7000.sh
build-core-armv7m7-imxrt106x.sh
build-core-ia32-generic.sh
build-core-riscv64-spike.sh
makes/binary.mk
makes/static-lib.mk

JIRA: CI-48
Probably won't build (or the result image won't be working) due to changes across multiple repositories

makes: install binaries into rootfs by make rules

---

makes/binary.mk
makes/static-lib.mk

makes: fix LOCAL_DIR when using templates in root Makefile

---

build-core-armv7a9-zynq7000.sh

JIRA: PD-119
Needed for rotrectangle user example

armv7a9-zynq7000: add building corelibs

---

toolchain/build-toolchain.sh

Due to building only stage1 compiler, our toolchain assumed libc
includes are broken. This resulted in generating "fixed" limits.h by the
toolchain (which was being included instead of libphoenix limits.h).
Build proper stage2 compiler (with some hacks not to rebuild whole gcc
and deps, just the relevant headers).
This is also a big step towards C++ support.
Other improvements:
- stripping result binaries
- enabled g++ compilation (libstdc++ is still missing due to broken
libphoenix)
Fixes phoenix-rtos/phoenix-rtos-project#113
**I would like to merge this soon, prepare necessary changes to docker image building and then test the full docker image**
**No immediate changes, but will require users to rebuild the toolchain - or copy it from the prebuilt docker image if they run linux :)**

toolchain: build proper stage2 compiler

---

build-core-armv7a7-imx6ull.sh

Needed for https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/121 to work.
JIRA: DTR-88

imx6ull: core: install headers needed to build filesystems first

---

Makefile.host

This is need to compile test binaries without all symbols resolved.
JIRA: ISM-61
This allows compiling executables without all symbols resolved. It is useful for building tests to avoid defining symbols that are not used in tested code.

host-pc: Add -ffunction-sections -fdata-sections flags

---

toolchain/build-toolchain.sh
toolchain/gcc-9.3.0-04-disable_tm.patch

Fixes needed for toolchain to be built in clean environment

Toolchain build fixes

---

build-core-armv7a7-imx6ull.sh
build-core-armv7m7-imxrt106x.sh
build-core-armv7m7-imxrt117x.sh
build-core-ia32-generic.sh

build-core: Don't build lwip, when CORE_NETWORKING_DISABLE is set

---

build.sh

Industry standard.
JIRA: DTR-242

build: don't build tests on 'all'

---

build-core-armv7a9-zynq7000.sh
build.sh

merge master into feature/syspage

---

Makefile.riscv64
build-core-riscv64-spike.sh

update riscv building process

---

makes/binary.mk
makes/static-lib.mk

Treat local "include" dir as "external API" - install all include files
in respective subfolders in PREFIX_H. Use local dir for lib/bin
compilation to avoid race conditions when there are cross-header
dependencies present within one component (needed for USB).
Feature enabled by default, to explicitly not install "include" subtree
- set LOCAL_HEADERS_DIR to non-existent directory.
- 
DONE: CI-59

makes: install external headers subtree from "include" dir by default

---

build-core-armv7a7-imx6ull.sh
build-core-armv7m7-imxrt106x.sh

JIRA: DTR-227
This is needed in order to install "usb" app to /sbin/ directory in rootfs.

core: Fix installing usb

---

build-core-armv7a7-imx6ull.sh

armv7a7-imx6ull: filesystems does not longer depend on libflashdrv

---

Makefile.armv7a

Fixes: phoenix-rtos/phoenix-rtos-project#402
PD-274

armv7a: split FPU settings for imx6ull and zynq7000

---

Makefile.armv7a

armv7a: add neon option to FPU and remove tabs

---

scripts/upload-zynq7000.gdb

- scripts: provide gdb upload script for zynq7000 architecture
- JIRA: PD-297

scripts: provide gdb upload script for zynq7000 architecture

---

build-core-armv7a9-zynq7000.sh

zynq: remove `plo` building before generating script files

---

build-core-armv7a7-imx6ull.sh
build-core-armv7a9-zynq7000.sh
build-core-armv7m4-stm32l4x6.sh
build-core-armv7m7-imxrt105x.sh
build-core-armv7m7-imxrt106x.sh
build-core-armv7m7-imxrt117x.sh
build-core-host-generic.sh
build-core-ia32-generic.sh
build-core-riscv64-generic.sh
build.sh
build.subr
scripts/mkimg-app-stm32.sh
scripts/mkimg-boot-zynq7000.sh
scripts/mkimg-imxrt.sh
scripts/mkimg-stm32.sh
scripts/program-stm32l4x6.sh
toolchain/build-toolchain.sh

Change the shebang to make build system more portable.

Change the shebang for bash scripts

---

Makefile.common

add multilib directory to linker paths
JIRA: PD-332

add multilib directory to linker paths

---

build.sh
makes/binary.mk
makes/static-lib.mk

fix global paths being included when variables are empty

---

Makefile.sparcv8leon3
build-core-sparcv8leon3-gr716.sh
makes/check-target.mk
toolchain/binutils-2.34-02-sparc-phoenix.patch
toolchain/build-toolchain.sh
toolchain/gcc-9.3.0-02-i386-pc-phoenix.patch
toolchain/gcc-9.3.0-06-libstdcpp.patch
toolchain/gcc-9.3.0-07-sparc-phoenix.patch
toolchain/gcc-9.3.0-08-sparc-mno-pditr.patch
toolchain/gcc-9.3.0-09-sparc-pic_crtstuff.patch

JIRA: RTOS-248
Create toolchain for Sparc Leon3 architecture
JIRA: RTOS-248

Toolchain port for Sparc Leon3

---

makes/static-lib.mk

makes: make sure binary.mk arguments are not passed to static-lib.mk

---

scripts/gr716-bch.py
scripts/gr716-convert.py

gr716: add script to generate bch for SPI image

---

Makefile.common
build.sh
target/armv7a.mk
target/armv7m.mk
target/ia32.mk
target/riscv64.mk
target/sparcv8leon3.mk

CI to pass: https://github.com/phoenix-rtos/phoenix-rtos-project/pull/834

makes: switch to linking by gcc

---

toolchain/build-toolchain.sh

toolchain: fix sysroot libc include paths after c++ includes moving

---

toolchain/gcc-9.5.0-07-sparc-phoenix.patch
toolchain/gcc-9.5.0-09-sparc-pic_crtstuff.patch

sparc toolchain: add multilib

---

scripts/upload-zynq7000-jlink.gdb
scripts/upload-zynq7000-smt2.gdb

It gives access to flash zynq7000 zedboard with Jtag and Jlink
JIRA: CI-364

scripts: add upload-zynq7000 via smt2 JTAG adapter

---

build-core-sparcv8leon3-gr712rc.sh
makes/include-target.mk
target/sparcv8leon3.mk
toolchain/build-toolchain.sh

add sparcv8leon3-gr712rc target

---

Makefile.common

- makefile.common: switch to abs path when compiling asm files
- makefile.common: create dependency files and compile in one command
Avoid printing additional preprocessor output when compiling host utils using clang

makefile.common: create dependency files and compile in one command

---

build-core-sparcv8leon3-gr712rc.sh

sparcv8leon3-gr712rc: build posixsrv

---

Makefile.common
target/host.mk

Makefile.common: adaptation for macOS

---

build-core-riscv64-generic.sh

JIRA: RTOS-550
This introduces warnings that are fixed in https://github.com/phoenix-rtos/phoenix-rtos-posixsrv/pull/23

riscv64: build posixsrv

---

target/riscv64.mk

JIRA: RTOS-550
Allow optimizations using builtin functions.
Verified that compiler doesn't do anything stupid.

riscv64: remove `-fno-builtin` flag

---

build-core-host-generic.sh

host-generic: install kernel headers

---

build-core-host-generic.sh

host-generic: Add libtinyaes to core build

---

toolchain/gcc-9.5.0-05-arm-pic_crtstuff.patch

Previous fix was incomplete, the `-march` parameter would either be in CC or in CFLAGS depending on how the make will be called.
JIRA: CI-453

toolchain: fix arm cortex subvariant check

---

toolchain/gcc-9.5.0-05-arm-pic_crtstuff.patch

Cherry-picking changes from master to release branch:
- toolchain: fix arm crtstuff .data in PIC mode
- toolchain: fix arm cortex subvariant check

toolchain: fix arm building issues

---

target/armv7m.mk

This changes adds generating .su files for all armv7m architectures, especially imxrt. 
.su files is useful to analyze stack usage by tools. It can be not reliable if lto will be enabled, which is not case now.

target: Add -fstack-usage for all armv7m architectures

---

build-core-armv8r52-mps3an536.sh
makes/include-target.mk
target/armv8r.mk

add support for ARMv8 Cortex-R52 (MPS3 AN536 platform)

---

target/armv8r.mk

target/armv8r.mk: add mtune flag

---

build-core-armv8m33-mcxn94x.sh
build.sh
makes/include-target.mk
target/armv7a.mk
target/armv8m.mk
target/host.mk
target/ia32.mk
target/riscv64.mk

JIRA: RTOS-881
https://github.com/phoenix-rtos/phoenix-rtos-project/pull/1120
https://github.com/phoenix-rtos/plo/pull/337
https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/222
https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/569
https://github.com/phoenix-rtos/phoenix-rtos-hostutils/pull/55
https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/132
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/508
https://github.com/phoenix-rtos/libphoenix/pull/371

Add armv8m support

---

build.sh

build.sh: add mkrofs to hostutils list

---

scripts/image_builder.py
scripts/nvm_config.py

- image_builder: fix `blob` command
- image_builder: small typing/linter fixes
JIRA: CI-494

image_builder: fix `blob` command

---

scripts/image_builder.py

image_builder: allow passing offset as numeric value

---

scripts/nvm_config.py

nvm_config: Reserve partition type (futurefs)

---

build-core-sparcv8leon-gr740.sh
makes/include-target.mk
target/sparcv8leon.mk
toolchain/build-toolchain.sh

JIRA: RTOS-883
- https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/389
- https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/632
- https://github.com/phoenix-rtos/phoenix-rtos-project/pull/1260
- https://github.com/phoenix-rtos/libphoenix/pull/401
- https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/143
- https://github.com/phoenix-rtos/phoenix-rtos-utils/pull/230
- https://github.com/phoenix-rtos/plo/pull/375
- https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/532
- https://github.com/phoenix-rtos/phoenix-rtos-build/pull/222
- https://github.com/phoenix-rtos/phoenix-rtos-filesystems/pull/143

add sparcv8leon-gr740 target

---

build-core-armv7r5f-zynqmp.sh
makes/include-target.mk
scripts/mkimg-boot-zynqmp.sh
target/armv7r.mk

Add armv7r5f-zynqmp target

---

target/sparcv8leon.mk

target/sparcv8leon/gr740: add LEON_USE_PWR define

---

build-core-ia32-generic.sh

JIRA: RTOS-970
https://github.com/phoenix-rtos/phoenix-rtos-usb/pull/34
https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/525

ia32: build usb stack

---

makes/static-lib.mk

makes: fix DEP_LIB typo in static-lib.mk

---

toolchain/build-toolchain.sh

It greatly reduces the total size of the toolchain (eg. arm-phoenix 1.2 GB -> 465 MB).
DONE: CI-537

toolchain: strip target libraries

---

build-core-armv8m55-stm32n6.sh
makes/include-target.mk
target/armv8m.mk

Add scripts necessary to build on armv8m55-stm32n6 target.
One of the changes that was necessary was adding an option to explicitly set the address where kernel data is stored. On STM32N6 if processor is in secure mode, RAM that can be used for data is in the 0x30000000 ~ 0x343c0000 range depending on configuration. Also, previous scripts were hard-coded for a Cortex-M33 target.

add armv8m55-stm32n6 target

---

build-core-armv7r5f-tda4vm.sh
makes/include-target.mk
target/armv7r.mk

add armv7r5f-tda4vm target
